name: luacheck
on:
  push:
    paths:
      - 'builtin/**.lua'
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - 'builtin/**.lua'
      - '.github/workflows/**.yml'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Luarocks
      run: |
        sudo apt-get update -qyy
        sudo apt-get install luarocks -qyy
    - name: Install Luacheck
      run: luarocks install --local luacheck
    - name: Run Luacheck
      run: $HOME/.luarocks/bin/luacheck builtin
